import Head from "next/head";
import { useState, useEffect } from "react";
import Card from "../components/Card";

export default function Home() {
  const [movies, setMovies] = useState([]);
  const [input, setInput] = useState("");

  function submitHandler(element) {
    element.preventDefault();
    if (!input) {
      return alert("Please enter keyword");
    }

    async function fetchData() {
      const response = await fetch(
        `https://www.omdbapi.com/?apikey=59d036c0&s=${input}`
      );
      const data = await response.json();
      const results = data.Search;
      setMovies(results);
    }
    fetchData();
  }

  return (
    <>
      <div className="container min-h-sreen mx-auto py-10 relative overflow-hidden px-3">
        <Head>
          <title>Website Database Movie</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <h1 className="text-3xl font-semibold">Web Movies</h1>

          <form onSubmit={submitHandler}>
            <input
              onChange={(e) => setInput(e.target.value)}
              type="text"
              placeholder="Search Movies"
              className="my-5 px-3 py-2 ring-2 ring-blue-500 focus:ring-2 focus:ring-slate-900 outline-none border-cyan-500 overflow-hidden rounded-lg w-full md:w-2/3 lg:w-1/3"
            />
            <button
              type="submit"
              className="px-3 py-2 bg-cyan-500 rounded-lg text-white hover:bg-cyan-400 -my-5 w-full md:my-0 md:mx-1 md:w-auto"
            >
              Search
            </button>
          </form>

          {typeof movies !== "undefined" ? (
            <div className="mt-10 grid grid-cols-2 md:grid-cols-5 md:mt-0 gap-2">
              {movies.map((movie) => (
                <Card
                  key={movie.imdbID}
                  poster={movie.Poster}
                  title={movie.Title}
                  year={movie.Year}
                  imdbID={movie.imdbID}
                />
              ))}
            </div>
          ) : (
            <div className="w-full mt-5">
              <h1 className="text-3xl text-red-500 text-center">
                Movies not found
              </h1>
            </div>
          )}
        </main>
      </div>
    </>
  );
}
